version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    ports:
      - "85:8080"
    volumes:
      - ./appImage/app:/usr/src/app
    command: ["npm", "run", "serve:dev"]

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
  appImages:
