version: '2'
services:
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    image: thomasmars/node
    ports:
      - "80:8080"
    links:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
  appImages:
